server:
  port: 8080

spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: Customer
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: AuthenticationFilter
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
          filters:
            - name: AuthenticationFilter
        - id: seller
          uri: http://localhost:8083
          predicates:
            - Path=/seller/**
          filters:
            - name: AuthenticationFilter
        - id: cart
          uri: http://localhost:8084
          predicates:
            - Path=/cart/**
          filters:
            - name: AuthenticationFilter
        - id: orders
          uri: http://localhost:8085
          predicates:
            - Path=/order/**
          filters:
            - name: AuthenticationFilter
        - id: search
          uri: http://localhost:8086
          predicates:
            - Path=/search/**
          filters:
            - name: AuthenticationFilter

